### ISSUE TITLE
f = (a+b) + (c+d) + d fails 

### ISSUE THREAD

**Issue by DerThorsten** [xtensor-stack/zarray#54]
I was playing a bit with zarray by creating some new tests and I got this one to fail.
Am I missing something or doing something stupid?  Looka like the last `+d` is ommited.
I added a pr with the failing test in #53  
```c++
    TEST(zfunction, math_operator_extended)
    {
        using add_dispatcher_type = zdispatcher_t<detail::plus, 2>;
        add_dispatcher_type::init();

        xarray<int> a = {{1, 1}, {1, 1}};
        xarray<int> b = {{2, 2}, {2, 2}};
        xarray<int> c = {{3, 3}, {3, 3}};
        xarray<int> d = {{4, 4}, {4, 4}};

        auto res = xarray<int>::from_shape({2, 2});

        zarray za(a);
        zarray zb(b);
        zarray zc(c);
        zarray zd(d);
        zarray zres(res);

        auto f = ((za+zb) + (zc+zd)) + zd;

        zassign_args args;

        f.assign_to(zres.get_implementation(), args);

        auto expected = xt::eval((a+b) + (c+d) + d);
        EXPECT_EQ(res, expected);
    }
```

**Comment by DerThorsten** [comment]
The brackets are important to make it fail:
This passes:
```
za+zb + zc+zd + zd;
```

This fails:
```
(za+zb) + (zc+zd) + ze;
```

**Comment by DerThorsten** [comment]
consider smth like
```
za =  expr_a + expr_b
```
This means we end up calling the following `assign_to_impl` right?
https://github.com/xtensor-stack/zarray/blob/bdad00ddbfcb0f9e35baf99f0f7822a283d70240/include/zarray/zfunction.hpp#L237

When I understand the logic behind `detail::get_array_impl` correct it tries to get the array impl for the arguments of the zfunction.
https://github.com/xtensor-stack/zarray/blob/bdad00ddbfcb0f9e35baf99f0f7822a283d70240/include/zarray/zfunction.hpp#L239 

In the example above these arguments are   ` expr_a , expr_b`.

The `detail:get_array_impl` ends up in `zfunction_argument<E>::get_array_impl(e, z, args)`.
`zfunction_argument` has a specialization for `zarray` and `zscalar_wrapper` and a fallback implementation which will be triggered if the argument is a zfunction.
This class looks like:
```c++
template <class E>
struct zfunction_argument
{
    static std::size_t get_index(const E& e)
    {
        return e.get_result_type_index();
    }

    static const zarray_impl& get_array_impl(const E& e, zarray_impl&expr_a + expr_b res, const zassign_args& args)
    {
        return e.assign_to(res, args);
    }
};
```
So in `get_array_impl` we assign  `e` to `res`.
So assume in our example  `za = expr_a + expr_b` bot `exp_b` and `expr_b` are zfunctions. This means  we assigned `expr_a` to `za` and `expr_b` to `za` before we call the dispatcher.
This seems a bit fishy to me.

**Comment by DerThorsten** [comment]
So with the results to which we assign and one additional buffer I can see how everything should work.
Basically one needs as many buffers as the maximum arity of the involved operations.

**Comment by JohanMabille** [comment]
Nice investigation!

Actually we need as many buffers as "terminal" nodes, i.e. nodes for which all children are leaves:

```cpp
zarray res = a + b + c + d; 
// only one temporary is required:
// tmp = a + b;
// tmp = tmp + c;
// tmp = tmp + d;


zarray res = (a + b) + (c + d);
// two temporaries are required:
// tmp1 = a + b;
// tmp2 = c + d;
// tmp1 = tmp1 + tmp2;
```

**Comment by DerThorsten** [comment]
I think #60 fixes this issue
